import argparse
import json
import os


def generate_readme(precision_data: dict, output_path: str):
    """Write a README file documenting the program structure and precision results."""
    content = f"""# Snapshot-Based Visual Homing

## Program Structure

This is a single-file implementation (`homing.py`) of the snapshot model for
visual place recognition and homing, based on Cartwright & Collett.

### Main Components

1. **Data Classes (`RetinaFeature`, `Retina`, `World`)**
   - Define the environment (three circular landmarks) and the circular retina
     representation.

2. **Retina Construction (`build_retina`)**
   - Projects landmarks from world coordinates onto the retina.
   - Alternates landmark arcs and gap arcs sorted by angle.
   - Handles overlapping landmarks robustly to prevent artificially large gaps.

3. **Matching (`match_feature`)**
   - Matches each snapshot feature to the closest feature of the same type
     (landmark/gap) in the current view.

4. **Vector Computation (`compute_component_vectors`, `homing_vector`)**
   - Computes tangential (turn) and radial (approach) components.
   - Combines them into a final normalized homing direction.

5. **Evaluation (`compute_homing_precision`)**
   - Compares the calculated homing vector against the ideal direction
     (straight line to home) for every grid point.
   - Reports mean, max, and standard deviation of the angular error.

6. **Visualization**
   - `plot_vector_field`: Generates the full grid map with all homing vectors.
   - `plot_precision_heatmap`: Optional heatmap of angular errors.
   - `HomingDiashow`: Interactive step-by-step view (optional, for debugging).

## How to Run

### Automatic Verification (Required)
Generate the vector-field plot and precision report:

```bash
python homing.py --mode auto --output ./output
```

This creates:
- `homing_vectors.png` — map of all homing vectors (task c)
- `precision.json` — precision data for external README generation
- `precision_heatmap.png` — optional error heatmap

### Interactive Diashow (Optional)
```bash
python homing.py --mode diashow --start -3.0 -1.0
```
Press **SPACE** to step through retina, pairing, individual vectors, sum vectors, homing vector, and movement.

## Homing Precision

| Metric | Value |
|--------|-------|
| Mean angular error | **{precision_data["mean_error_deg"]:.4f}°** |
| Maximum angular error | **{precision_data["max_error_deg"]:.4f}°** |
| Standard deviation | **{precision_data["std_dev_deg"]:.4f}°** |

The precision is calculated over the full 14×14 grid (excluding the home
position at (0,0)) by comparing the ideal homing direction (straight line to
home) with the direction computed by the snapshot model.
"""
    with open(output_path, 'w', encoding='utf-8') as file:
        file.write(content)
    print(f"[INFO] README saved to: {output_path}")


def main():
    parser = argparse.ArgumentParser(
        description="Generate README.md from precision.json"
    )
    parser.add_argument(
        "--input",
        default="./output/precision.json",
        help="Path to the precision JSON file generated by homing.py"
    )
    parser.add_argument(
        "--output",
        default="./output/README.md",
        help="Path where the README.md should be written"
    )

    args = parser.parse_args()

    with open(args.input, 'r', encoding='utf-8') as file:
        precision = json.load(file)

    generate_readme(precision, args.output)


if __name__ == "__main__":
    main()
